### ISSUE TITLE
add HSV

### ISSUE THREAD

**Issue by safareli** [sharkdp/purescript-colors#23]
```purescript
toHSVA :: Color.Color -> {h :: Number, s :: Number, v :: Number, a :: Number}
toHSVA color = case Color.toHSLA color of
  ({h, s, l, a}) ->
    let
      s' = s * (if l < 0.5 then l else 1.0 - l)
    in
      { h
      , s: 2.0 * s' / (l + s')
      , v: l + s'
      , a
      }

hsva :: Number → Number → Number → Number → Color.Color
hsva h s v a = Color.hsla h s' l a
  where
  tmp = (2.0 - s)*v
  s' = s * v / (if tmp < 1.0 then tmp else 2.0 - tmp)
  l = tmp / 2.0

hsv :: Number → Number → Number → Color.Color
hsv h s v = hsva h s v 1.0
```
adopted from https://gist.github.com/xpansive/1337890

**Comment by safareli** [comment]
If you know some more elegant implementation let me know.
Will open PR shortly.

**Comment by safareli** [comment]
Actually this conversion function is not what i wanted as it is not lossless I.e.:
If I have `hsl(0,100%,0%)` I expect to get `hsv(0,100%,0%)`  or 
If I have `hsl(0,50%,0%)` I expect to get `hsv(0,66.6%,0%)` 

But all algorithms I found:

http://ariya.blogspot.com/2008/07/converting-between-hsl-and-hsv.html
https://stackoverflow.com/questions/3423214/convert-hsb-hsv-color-to-hsl

Involve multiplication which results in `hsv(0,0%,0%)`, they loose `s` when color is black.

**Comment by sharkdp** [comment]
> Actually this conversion function is not what i wanted as it is not lossless

I think this is something we could tolerate. It's related to this comment in `src/Color.purs`:
``` purs
-- | The representation of a color.
-- |
-- | Note:
-- | - The `Eq` instance compares two `Color`s by comparing their (integer) RGB
-- |   values. This is different from comparing the HSL values (for example,
-- |   HSL has many different representations of black (arbitrary hue and
-- |   saturation values).
-- | - Colors outside the sRGB gamut which cannot be displayed on a typical
-- |   computer screen can not be represented by `Color`.
-- |
data Color = HSLA Number Number Number Number
```

This means that - given the current `Eq` instance - those colors would still be the same after converting back and forth(?).

**Comment by safareli** [comment]
Yah I have red that and that's fine from Eq perspective.

But I wanted it to be "lossless" as I wanted it for color picker module, which showed HSV square like in photoshop.

So when users choices a color I know HSV values but as color stores only HSL version I can't use just color in my state (as I want to read exact same HSV values back to show pointer on color picker).

I believe there would be a way to convert HSV to HSL without losing data, but I haven't found one and it was not trivial for me, so I stooped.

Do you know any lossless implementation of HSV <-> HSL?

I just thought: maybe converting HSV to XYZ, Lab or LCh and then to HSL will solve the looseness issue? (I don't understand this color formats will need to play with converters to check it)

**Comment by sharkdp** [comment]
> Do you know any lossless implementation of HSV <-> HSL?

I don't... but what about just adding a special case for *V=0*?

In the HSL representation, `hsl(H, S, 0) = hsl(0, 0, 0) = black` for all values of *H* ans *S*. This means, that we are free to choose values for *S* (and *H*) if *L = 0*. So in this case (when *V=0* and therefore *L=0*), we can simply choose the value for *S* to be what the formula tells us in the proper limit of *V -> 0*, which is:

*S = S_HSV / (2 - S_HSV)*

What do you think?

**Comment by safareli** [comment]
How do you know that `S = S_HSV / (2 - S_HSV)` ? (like can you give a link or something as I couldn't find such relation before)

Given `S = S_HSV / (2 - S_HSV)` , `S_HSV = 2 * S / (1 + S)`:
```
S = S_HSV / (2 - S_HSV)
(2 - S_HSV) * S = S_HSV
(2 - S_HSV) * S / S_HSV = 1
2 * S / S_HSV - S_HSV * S / S_HSV = 1
2 * S / S_HSV - S = 1
2 * S / S_HSV = 1 + S
2 * S = (1 + S) * S_HSV
2 * S / (1 + S) = S_HSV -- BINGO
2 * S = (1 + S) * S_HSV
2 * S = S_HSV + S * S_HSV
2 * S - (S_HSV + S * S_HSV) = 0
2 * S - S_HSV - S * S_HSV = 0
(2 - S_HSV) * S - S_HSV = 0
(2 - S_HSV) * S = S_HSV
S = S_HSV / (2 - S_HSV)
```

So I have updated code and it works fine, will open PR shortly:

```purescript
toHSVA :: Color.Color -> {h :: Number, s :: Number, v :: Number, a :: Number}
toHSVA color = case Color.toHSLA color of
  ({h, s, l, a}) ->
    if l == 0.0 then
      { h
      , s: 2.0 * s / (1.0 + s)
      , v: 0.0
      , a }
    else
      let
        s' = s * (if l < 0.5 then l else 1.0 - l)
      in
        { h
        , s: 2.0 * s' / (l + s')
        , v: l + s'
        , a
        }

hsva :: Number → Number → Number → Number → Color.Color
hsva h s v a = Color.hsla h s' l a
  where
  tmp = (2.0 - s)*v
  s' =
    if v == 0.0
    then s / (2.0 - s)
    else s * v / (if tmp < 1.0 then tmp else 2.0 - tmp)
  l = tmp / 2.0

hsv :: Number → Number → Number → Color.Color
hsv h s v = hsva h s v 1.0
```

**Comment by sharkdp** [comment]
> How do you know that S = S_HSV / (2 - S_HSV) ?

I calculated the limit for `v -> 0`. Take a look at `tmp = (2.0 - s)*v`. If `v -> 0`, we have `tmp -> 0`. So the if-clause in `(if tmp < 1.0 then tmp else 2.0 - tmp)` will always evaluate to the first expression `tmp`. This, in turn, yields `s' = s * v / tmp = s * v / ((2.0 - s)*v) = s / (2.0 - s)`

**Comment by safareli** [comment]
Nice! need to revisit calculus :D  

The snippet I have here is not quite right, in the PR #27  I have added tests and cople edge cases
