### ISSUE TITLE
can't run tests

### ISSUE THREAD

**Issue by safareli** [sharkdp/purescript-colors#24]
Can’t run tests as purescript-colors depends on purescript-flaredoc and purescript-flaredoc depends on purescript-colors, so when I run `pulp test` I get:
```
[1/9 DuplicateModule] 

  Module Color has been defined multiple times:
  
    /dev/purescript-colors/bower_components/purescript-colors/src/Color.purs line 1, column 1 - line 578, column 20
    /dev/purescript-colors/src/Color.purs line 1, column 1 - line 578, column 20
```

**Comment by safareli** [comment]
`justinw` on FP slack suggested to remove `bower_components/purescript-colors` and it worked but I think that's not good :d

**Comment by sharkdp** [comment]
That's what I've been doing so far, yes. Since this only affects the (interactive) tests, I think it's okay - but definitely not pretty, no.

As I don't see any way to fix this currently, I'm closing this ticket. I've added a comment in the README.

**Comment by safareli** [comment]
This works as long as there is no braking change in API, in which case it would be tedious to run tests. i.e. it's impossible to have travis or some other CI integration.
I think some different the test lib should be used for testing here.

**Comment by sharkdp** [comment]
Please note that the unit tests work perfectly fine. It's just the interactive documentation that depends on flaredoc.
