### ISSUE TITLE
add 'cubehelix' colour scheme

### ISSUE THREAD

**Issue by safareli** [sharkdp/purescript-colors#30]
I came across ['cubehelix' colour scheme](https://www.mrao.cam.ac.uk/~dag/CUBEHELIX/).
[This page](https://www.mrao.cam.ac.uk/~dag/CUBEHELIX/cubetry.html) shows how different parameters effect the scheme. it would be great if we can reconstract that configuration in some object and then define something like `cubehelix:: CubehelixConfig -> ColorScale`.
[Here is python](https://github.com/jradavenport/cubehelix/blob/master/cubehelix.py) implementation, on original page there are cople more.

**Comment by sharkdp** [comment]
:+1:
